### ISSUE TITLE
References to external sources (URLs, books, magazines)

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#10]
Add support for references to external sources.

Acceptance criteria:
1. References to external sources (URLs) can be added to the syllabus content in MD files by using defined syntax
2. References to books and magazines can be added to the syllabus content in MD files by using defined syntax
3. Way how to add references is documented
4. References to books and magazines are shown in the text as in format like [Beizer(1990)]
5. List of References is generated at the end of the document as a separate chapter

**Comment by Witiko** [comment]
> References to books and magazines are shown in the text as in format like [Beizer(1990)]

How much flexibility is there? Are standard author-year references like (Beizer, 1990) acceptable?

> List of References is generated at the end of the document as a separate chapter

Are there any criteria on the bibliographic style used in the list of references? Specifically, can we use ISO 690?

**Comment by danopolan** [comment]
> How much flexibility is there? Are standard author-year citations like (Beizer, 1990) acceptable?
Yes, author-year citations are fine,
> Are there any criteria on the bibliographic style used in the list of references? Specifically, can we use ISO 690?
Sure, let's follow ISO 690.

**Comment by Witiko** [comment]
Here is how a reference to a book would be written:

``` bib
@book{beizer,
  author = {Boris Beizer},
  title = {Software Testing Techniques},
  year = {1990},
  publisher = {Van Nostrand Reinhold: Boston MA},
  volume = {2}
}
```

@danopolan, in the acceptance criteria, you also mention articles and external sources (URLs). Should I include examples for these as well? I can also include a reference to the BibLaTeX manual, which describes the syntax of BIB files and the possible reference types in great detail.

Here is what a citation of the book would look like in text:

``` md
Software systems are an integral part of life [@beizer], from business applications (e.g., banking) to
consumer products (e.g., cars). Most people have had an experience with software that did not work as
expected. Software that does not work correctly can lead to many problems, including loss of money, time,
or business reputation, and even injury or death. Software testing is a way to assess the quality of the
software and to reduce the risk of software failure in operation.
```

![image](https://github.com/danopolan/istqb_latex/assets/603082/504e8754-f2d1-4bad-94cd-c058b01d6fea)

Here is what a list of references would look like:

![image](https://github.com/danopolan/istqb_latex/assets/603082/dee4be49-c37c-4221-bfe5-766a6f4f862b)

@danopolan, does this look acceptable?

**Comment by danopolan** [comment]
@Witiko this looks great. But yes, if you can please add some example reference to the online source.
Data from ISTQB CTFL module could be used here:
E.g. "Brykczynski, B. (1999) “A survey of software inspection checklists,” ACM SIGSOFT Software Engineering
Notes, 24(1), pp. 82-89"
I wonder how this will be recorded in the BibLaTeX.

Also, if is possible to split bibliography into more sections, under one chapter? Per ISTQB template there are Standards, ISTQB Documents, Books and Articles. See image below.

![image](https://github.com/danopolan/istqb_latex/assets/95688217/1f3e6e9c-a8c8-4686-9076-9ff1976bdb54)

**Comment by Witiko** [comment]
> Per ISTQB template there are Standards, ISTQB Documents, Books and Articles.

You mentioned websites. Where do these go?

Can you please provide an example of an ISTQB® Document that I could cite in the ISTQB® Documents section?

**Comment by danopolan** [comment]
You can see the example in CTFL ISTQB syllabus on page 62
https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB_CTFL_Syllabus-v4.0.pdf

But it does look like following
Marick, B. (2003) Exploration through Example, http://www.exampler.com/oldblog/2003/08/21.1.html#agile-testing-project-1

We do not have to match the specific format as used in ISTQB syllabus right now. We can use ISO 690, but make it close to how it looks like now if ISO allows that. So basically, get better, but not totally different :)

**Comment by Witiko** [comment]
> @Witiko this looks great. But yes, if you can please add some example reference to the online source.
> Data from ISTQB CTFL module could be used here:
> E.g. "Brykczynski, B. (1999) “A survey of software inspection checklists,” ACM SIGSOFT Software Engineering
> Notes, 24(1), pp. 82-89"
> I wonder how this will be recorded in the BibLaTeX.

The example reference would be recorded as follows:

``` bib
@article{brykczynski:1992,
  author = {Bill Brykczynski},
  title = {A survey of software inspection checklists},
  year = {1992},
  journal = {{ACM SIGSOFT} Software Engineering Notes},
  volume = {24},
  number = {1},
  pages = {82-89}
}
```

Here is what the reference would look like when formatted using ISO 690:

![example](https://github.com/danopolan/istqb_latex/assets/603082/42a461ff-cafc-4d1b-bf9a-9e35d8158f56)

However, this is not a web page / online source, but a journal article.
Therefore, I also added Marick (2003) that you mentioned in https://github.com/danopolan/istqb_latex/issues/10#issuecomment-1614227986:

``` bib
@online{marick:2013,
  author = {Brian Marick},
  title = {Exploration through Example},
  date = {2003-08-21},
  url = {http://www.exampler.com/old-blog/2003/08/21/},
  urldate = {2023-07-11},
}
```

Here is what the reference would look like when formatted using ISO 690:

![example](https://github.com/danopolan/istqb_latex/assets/603082/84f9de1f-9a39-4d12-88fc-b1c63870569a)

Furthermore, I also added a standard and an ISTQB® document for completeness:

``` bib
@report{iso-iec:2022,
  institution = {International Organization for Standardization},
  title = {Software and systems engineering -- Software testing},
  subtitle = {Part 1: General Concepts},
  date = {2022-01},
  type = {Standard},
  volume = {2022}
}
```

![example](https://github.com/danopolan/istqb_latex/assets/603082/c8a648b6-336a-4a77-95b1-68d562a999cd)

``` bib
@misc{istqb:2023,
  title = {Certified Tester},
  subtitle = {Foundation Level Syllabus},
  date = {2023-04-21},
  note = {Version 4.0},
  keywords = {istqb}
}
```

![example](https://github.com/danopolan/istqb_latex/assets/603082/8896ac91-1dfd-429d-a2fd-31c3ee5aae20)

> Also, if is possible to split bibliography into more sections, under one chapter?

I made the references look as follows:

![example](https://github.com/danopolan/istqb_latex/assets/603082/7a0694c6-3908-4cf1-87c1-b1fa29b24cf2)

Here is how citations look in the text:

``` md
Here are example citations for standards [@iso-iec:2022], ISTQB documents [@istqb:2023], books [@beizer:1990], journal articles [@brykczynski:1992], and web pages [@marick:2013]. For instructions on writing your own references to `example.bib`, see the Bib\LaTeX{} manual [@kime:2023, Chapter 2]. The full list of references is shown at the end of this document.
```

![example](https://github.com/danopolan/istqb_latex/assets/603082/e372197e-3297-4b81-a1f8-f8cca5f113de)

Does this meet your acceptance criteria, @danopolan?
