### ISSUE TITLE
References to internal sections

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#11]
Add support for references between chapters defined in various MD files.

Acceptance criteria:
1. Author is able to reference any chapter within the syllabus in text defined in Markdown
2. References works as link with custom text
3. References are somehow differentiated from other text, so it's obvious for the user, he can click on it

**Comment by Witiko** [comment]
@danopolan In file `example-istqb-content.md`, there is the following section:

https://github.com/danopolan/istqb_latex/blob/a01c13e737d28ee43206fbc4e9d1777a8b2f5e19/example-istqb-content.md?plain=1#L14-L22

For the former part of this section, the Markdown package has no support for referencing entire MD files. However, we can easily produce internal links to sections with custom text by using [header attributes][2] and markdown links:

``` md
## Seven Testing Principles {#seven-testing-principles}
A number of testing principles have been suggested over the past 50 years and offer general guidelines common for all testing.

[...]

Section links with custom text:

- Link to [testing principles](#section:Seven-Testing-Principles) should redirect you to the section Seven Testing Principles in this MD document.  
- Link to [another file section](#section:section-no1) will redirect you to the Section 1 in other MD document.  
```

![image](https://github.com/danopolan/istqb_latex/assets/603082/2753cdb4-b876-4af3-9b8e-0d784ab1c85c)

Is this sufficient? The acceptance criteria of this pull request do not mention the necessity for referencing entire MD files.

For the latter part of this section, we can also avoid LaTeX by using [header attributes][2] and [relative references][1]:

``` md  
Section references:

- Link to <#section:seven-testing-principles> should redirect you to the section Seven Testing Principles in this MD document.  
- Link to <#section:section-no1> will redirect you to the Section 1 in other MD document.  
- Link to <#section:fundamentals-of-testing> will redirect you to the the head of another MD document.
```

![image](https://github.com/danopolan/istqb_latex/assets/603082/0963d338-77bd-4a52-9b7c-f94a2d342462)

The acceptance criteria of this PR don't mention this style of references, but they are consistent with the references to tables and figures. Do we want to support them in the template and include them in the example document?

 [1]: https://witiko.github.io/markdown/#option-relativeReferences
 [2]: https://witiko.github.io/markdown/#option-headerAttributes

**Comment by Witiko** [comment]
Not a problem, here is how the above section would look after hiding the red borders and after using italics for links:

![image](https://github.com/danopolan/istqb_latex/assets/603082/823fe52b-7567-489a-bf5d-1f493727fb38)

The entire italic text is clickable.

**Comment by danopolan** [comment]
Great. This is what I am looking for :)
