### ISSUE TITLE
Index of keywords

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#16]
Add the possibility to add an Index at the end of the syllabus document.

Acceptance criteria:
1. Index of words can be added to the end of the document
2. Way how to add words to the index and how to generate the index is documented
3. Index items are ordered alphabetically is in English language

**Comment by Witiko** [comment]
> Way how to add words to the index and how to generate the index is documented

By "documented", do you mean "used and commented on in the example document", or do we want to carry a separate documentation (user manual) as well?

**Comment by danopolan** [comment]
For now, we can keep all the documentation as part of the example document.
