### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#17]
Define a landing page according to the ISTQB syllabus template in MS Word Template.

Acceptance criteria:
1. Landing page follows the standard layout defined in the template
2. Data for the Landing page (syllabus name, version, date) are defined in one place

**Comment by danopolan** [comment]
Please follow the Syllabus Template in MS Word (`Syllabus template 3.21.docx`) that is a single source of truth for the whole LaTeX project

**Comment by Witiko** [comment]
Just wanted it confirmed here for clarity and future reference, since the ticket mentions both the ISTQB syllabus template in MS Word and the CTFL 4.0 syllabus.

**Comment by danopolan** [comment]
Oh my mistake. Corrected.
