### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#30]
Create a Copyright notice section which will be sourced from specific MD file e.g. acknowledgement.md

Acceptance criteria

1. Acknowledgements notice section is part of a final document
2. This section doesn't have section number assigned but is available in ToC
3. It's the fifth part of the document (after Table of Content)
4. Content of the section can be defined in md file

**Comment by Witiko** [comment]
An unnumbered acknowledgements section is already part of atlas.tex in #33.
