### ISSUE TITLE
Headings alignment

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#45]
Headings should be align to the left with text. Currently these is a small indent.
![Screenshot_20230720_072424_com google android apps docs](https://github.com/danopolan/istqb_latex/assets/95688217/4e7fcac8-6423-4441-809b-5ae94e21e4ac)

Headings should not be left at the end of one page without a following text. 
![Screenshot_20230720_072504_com google android apps docs](https://github.com/danopolan/istqb_latex/assets/95688217/51879c5d-e499-47fd-8724-c2bea36633ac)

Some headings has a text overflow.
![Screenshot_20230720_072531_com google android apps docs](https://github.com/danopolan/istqb_latex/assets/95688217/f0872520-4f52-41e1-844d-d94ea8a885c6)

**Comment by Witiko** [comment]
> Headings should be align to the left with text

There does not seem to be a consistent design spec, see the MS Word template:

![image](https://github.com/danopolan/istqb_latex/assets/603082/793b4d78-066c-4e16-9e22-12f6e0bbbfbf)

See also ISTQB_CTFL_Syllabus-v4.0.pdf:

![image](https://github.com/danopolan/istqb_latex/assets/603082/834d009e-d9d5-4a42-9949-5badfb09c488)

Both are indented, although there is an inconsistency in subsections, which MS Word outdents and ISTQB_CTFL_Syllabus-v4.0.pdf indents.

I will align the section and subsections with the left margin. Do you have any specific requirements as to how the headings should be aligned on the right? Currently, both MS Word and ISTQB_CTFL_Syllabus-v4.0.pdf outdents the headings to the right margin, but we can align the headings with both the left margin and the right margin if you would like.
