### ISSUE TITLE
Tables formatting

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#46]
We need to update how tables are rendered. Currently, there are two issues.

Tables should have all border lines rendered. Including vertical ones.
![Screenshot_20230720_073342_com google android apps docs](https://github.com/danopolan/istqb_latex/assets/95688217/18262355-7789-4107-9002-4906794d3247)

Some tables are wider than a page.
![Screenshot_20230720_073228_com google android apps docs](https://github.com/danopolan/istqb_latex/assets/95688217/6fc5b334-5784-4a28-8291-32d5f41809b1)

**Comment by Witiko** [comment]
Would you be happy with the formatting that is currently used for the revision history, see https://github.com/danopolan/istqb_latex/pull/43#issue-1812763946?

**Comment by Witiko** [comment]
You would be able to specify one or several columns that a) would stretch to the text width and b) could span several lines if needed as follows:

``` tex
| A narrow left-aligned column | A column that fits the remainding width and can span multiple lines |
|:--|---|
| foo | bar |
```

Here, the stretching is given by specifying the default alignment (`|---|`).

**Comment by Witiko** [comment]
There will need to be a code change, the formatting is currently only applied to Revision History. I will prepare a PR.
