### ISSUE TITLE
Bibliography split into References and Further Reading 

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#48]
Upon further discussing with ISTQB Product Owner and you were right about splitting cited and non-cited references.

Cited will be in References section with categorization into Standards, ISTQB Documents, Books, Articles.
Non-cited will be in Further Reading section right behind the References section with no categorization. Just a list of references.

**Comment by Witiko** [comment]
> Cited will be in References section with categorization into Standards, ISTQB Documents, Books, Articles.

Currently, there are *Articles and Web Pages* instead of *Articles*. Do we rename the section? Should `@online` references to web pages spill over to *Further Readings* as well, or do we keep them in section *Articles*?

**Comment by danopolan** [comment]
I would honetly remove Web Pages section and keep it as Articles only. We have discussed this yesterday with ISTQB Product Owner and she said, we can remove Web Pages, since there is no actual use for it now.
So we will change all references of type `online` to `article` in bib files.
