### ISSUE TITLE
Chapter content should start on a new page

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#79]
With the latest changes in the LaTeX code, there was a defect introduced, which keeps syllabus chapter content (starting with heading level 2) on the same page as the chapter intro (starting with level 1 heading). 
Chapter content has to start on a new page despite it starting with a level 2 heading, but is defined in a separate file. Or please introduce a way to force this by some markup in the Markdown format.

![image](https://github.com/danopolan/istqb_latex/assets/95688217/664730d4-4cba-46d5-81e7-20e5f0a1e364)

**Comment by Witiko** [comment]
I assume we want to start the new page to separate the content from the learning objectives, i.e. it we should add a page break after learning objectives.

For example, Appendix A of ATLaS does not contain learning objectives:

![image](https://github.com/danopolan/istqb_latex/assets/603082/f2f8af3b-53e4-4051-8b88-d0651c3ca29f)

Here, I assume we don't want to add a page break before section 6.1.

If this is a correct assumption, then https://github.com/danopolan/istqb_latex/pull/81 fixes this issue by adding a page break after learning objectives.
